title: Website ni Marco Enrico - Marco Enrico’s Website
description: Ang muntik sulok ng web ni Marco Enrico. - Marco Enrico’s little corner of the web.
url: "https://marcoenri.co"
email: mvalviar(at)gmail(dot)com
author: Marco Enrico

# Build settings
markdown: kramdown
input: GFM
syntax_highlighter: rouge

gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
