title: Marco Enrico
description: "Web Dev"
email: mvalviar(at)gmail(dot)com
author: Marco Enrico

name: "Marco Enrico"

# Build settings
markdown: kramdown
input: GFM
syntax_highlighter: rouge

gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
